config/routes.rb
DeloreanTestBed::Engine.routes.draw do
  resources :flux_capacitor, only: %w(index) do
    collection do
      post :start
      post :pause
      post :flux
      post :accelerate_to_eighty_eight
    end
  end
  root to: 'flux_capacitor#index'
end

app/controllers/delorean/application_controller.rb
module Delorean
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/delorean_test_bed/application_controller.rb
module DeloreanTestBed
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/delorean_test_bed/flux_capacitor_controller.rb
require_dependency "delorean_test_bed/application_controller"

module DeloreanTestBed
  class FluxCapacitorController < ApplicationController
    def index
      @scale = DeloreanTestBed::cache.read(:future).to_i
    end

    def start
      DeloreanTestBed::cache.write(:start, Time.now)
      Timecop.return
      redirect_to root_path
    end

    def pause
      DeloreanTestBed::cache.write(:pause, Time.now)
      Timecop.freeze(DeloreanTestBed::cache.read(:pause))
      redirect_to root_path
    end

    def flux
      DeloreanTestBed::cache.write(:scale, params[:scale])
      Timecop.scale(params[:scale].to_i)
      redirect_to root_path
    end

    def accelerate_to_eighty_eight
      DeloreanTestBed::cache.write(:future, DateTime.new(
        *params[:date].values.map(&:to_i)
      ))
      Timecop.travel(DeloreanTestBed::cache.read(:future))
      redirect_to root_path
    end
  end
end

app/helpers/delorean/application_helper.rb
module Delorean
  module ApplicationHelper
  end
end

app/helpers/delorean/flux_capacitor_helper.rb
module Delorean
  module FluxCapacitorHelper
  end
end

app/views/delorean_test_bed/flux_capacitor/index.html.erb
<%= button_to 'Time Circuits On (Start)', action: :start %>
<%= button_to 'Time Circuits Off (Stop)', action: :pause %>
<fieldset>
  <%= form_tag flux_flux_capacitor_index_path do %>
    <%= number_field_tag :scale, @scale || 0, { type: :integer, scale: 1} %>
    <%= submit_tag 'Fluxing' %>
  <% end %>
</fieldset>
<fieldset>
  <%= form_tag accelerate_to_eighty_eight_flux_capacitor_index_path do %>
    <%= select_datetime %>
    <%= submit_tag 'Accelerate' %>
  <% end %>
</fieldset>

app/views/layouts/delorean/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delorean</title>
  <%= stylesheet_link_tag    "delorean/application", media: "all" %>
  <%= javascript_include_tag "delorean/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>